### ISSUE TITLE
Step Functionsの使い方を調査する

### ISSUE THREAD

**Issue by appirits-watanabe** [yoshioka240/komatch#22]

**Comment by appirits-okubo** [comment]
![スクリーンショット 2020-08-14 18 06 01](https://user-images.githubusercontent.com/68407784/90234321-76379b00-de5a-11ea-8838-d411ee0189d7.png)
![スクリーンショット 2020-08-14 18 09 06](https://user-images.githubusercontent.com/68407784/90234338-7f286c80-de5a-11ea-942a-8a35c0ed593c.png)
![スクリーンショット 2020-08-14 18 14 22](https://user-images.githubusercontent.com/68407784/90234615-ed6d2f00-de5a-11ea-8886-ec2aeeba3abc.png)
![スクリーンショット 2020-08-14 18 11 31](https://user-images.githubusercontent.com/68407784/90234648-f9f18780-de5a-11ea-9661-030c52cf1913.png)
![スクリーンショット 2020-08-14 18 11 36](https://user-images.githubusercontent.com/68407784/90234691-0970d080-de5b-11ea-9c4a-5ea2ca1dcfd5.png)
![スクリーンショット 2020-08-14 18 14 00](https://user-images.githubusercontent.com/68407784/90234574-da5a5f00-de5a-11ea-9e71-9b06d3602983.png)
![スクリーンショット 2020-08-14 18 12 12](https://user-images.githubusercontent.com/68407784/90234711-11c90b80-de5b-11ea-8ebb-d8c5b0f6f6f4.png)

**Comment by appirits-okubo** [comment]
[AWS Step Functions: はじめてのAWS Step Functions – ステートマシンの実行](https://dev.classmethod.jp/articles/aws-step-functions-getting-started/)

**Comment by appirits-okubo** [comment]
[AWS Step Functions でサーバーレスワークフローを作成する](https://aws.amazon.com/jp/getting-started/hands-on/create-a-serverless-workflow-step-functions-lambda/)

**Comment by appirits-watanabe** [comment]
ありがとうございました
